### ISSUE TITLE
add luke's intan software to buzcode

### ISSUE THREAD

**Issue by dlevenstein** [buzsakilab/buzcode#144]
@evilrobotxoxo improved the intan software, should be added to buzcode?

**Comment by brendonw1** [comment]
I'd say yes

**Comment by DavidTingley** [comment]
I disagree, this breaks with any future development Intan does. It also encourages the bad practice of multiple data types within a single file.  Rather, going forward we should adjust neuroscope to integrate multiple data sources.

**Comment by brendonw1** [comment]
Maybe we can have a repo of stuff that’s useful but not fully supported. Or
a second repo

**Comment by DavidTingley** [comment]
+1 for keeping this separate. I don't think we should adopt it in the lab as it introduces versioning issues and creates a file format that is ambiguous to data type.  multiple *.dats for different data types is clearly the way to go in the future (though more painful in the short term in switching from amplirec and changing neuroscope).

**Comment by brendonw1** [comment]
... assigned to me :)... Sure.
Let's decide as a group
Basically I think Luke's code seems really practical, but I also think
David has some important points about version, support, compatibility, etc.

But I'd use this case to talk about how to handle these sorts of cases more
generally: cases where we have software that some people like but maybe it
doesn't fit into the scope or mission of buzcode.  What should we do?
Should we think of buzcode as a matlab package like FMAToolbox and so it
doesn't make reference to anything external?   Or do we think of it as a
general resource for anyone wanting to do BuzsakiLab-like analysis and so
we include a broader range of items like pointers to other repos, anything
anyone wrote that was good etc etc?
   Also how far does it extend "down" into things like clustering or basic
data "pre"processing?  Does it stay high-level like FMA?
   Maybe an in-between solution in dealing with code like Luke's or like
Peter's phy modifications or others is to have a text list of other
resources?  We could have pointers to git repo's and maybe a couple
sentences about how the things at that repo can be used in a way that
integrates with other things buzcode does?

This issue has come up probably half a dozen times in the last year, so it
seems like it's worth agreeing on a good way of handling it that both
doesn't ruin anything but is also useful in an optimal way.

Brendon

**Comment by brendonw1** [comment]
Did anything ever happen with this? Or will Luke put it somewhere on his
own?
It seems very useful to me and I’d like to use it.

B

**Comment by evilrobotxoxo** [comment]
The conclusion was that I'm going to set up my lab's github page and post
it there. That will happen, someday. For now, if you want the software, I
put it on dropbox and sent out links in an old email. If you can't find
them, let me know, and I can send them to you again.

Luke


Lucas L. Sjulson, MD, PhD
Assistant Professor
Department of Psychiatry and Behavioral Sciences
Dominick P. Purpura Department of Neuroscience
Albert Einstein College of Medicine
Rose F. Kennedy Center, Room 227
1410 Pelham Parkway South, Bronx, NY 10461
cell: 646-528-9672
http://sjulsonlab.org

**Comment by brendonw1** [comment]
Sounds good to me.  I think this is the link you sent:
https://www.dropbox.com/s/tzoc7kly7or54o8/Intan_Buzsaki_v2.zip?dl=0

And as a review the main changes are (If I'm correct):
- Analogin is now int16 rather than uint16 (same voltage range though, just
1 bit less resolution)
- All are saved to one output .dat - amplifier_analogin_auxiliary.dat

Right?

By the way, do you or anyone else know what happens if we need to use Intan
2.0 type software (ie with new hardware)?

Thank you again

Brendon

**Comment by brendonw1** [comment]
Oh and some new kind of metadata will be necssary for htis... like channel
ID info for instance... channel 129 is opto stim, channel 130 is camera
frames etc.

For either Luke's system or more generally in Peter's/sessionInfo systems
do we already have a way of identifying non-ephys channels?

**Comment by evilrobotxoxo** [comment]
The main changes are:

- analogin is now int16 instead of uint16, and the values are divided by 2
relative to before. Before, a 0 -> 3.3 V inputs mapped onto 0 -> 2^16
outputs. Now 0 - 3.3 V inputs maps to 0 -> 2^15 outputs.
- the auxiliary (accelerometer) is the same thing, now int16 instead of
uint16, and output values go between 0 -> 2^15 instead of 0 -> 2^16
- I haven't looked at v2.0 of the intan software, but I suspect the code
that writes the dat files is the same, so it should be easy to make the
same changes there as well

Luke

**Comment by brendonw1** [comment]
Thanks Luke... and actually here's the newer link you sent (I used the
initial one by mistake)

https://www.dropbox.com/s/6qrwbo7yy2yyywd/Intan_Buzsaki_v2-20180216.zip?dl=0
