### ISSUE TITLE
sleepscoremaster scores too much REM

### ISSUE THREAD

**Issue by DavidTingley** [buzsakilab/buzcode#148]
In recordings without sleep, or without cortical electrodes, I've noticed sleepscoremaster scores most wake epochs as REM state (>50% of some recordings). Is there a way we can limit/change this?

Maybe when REM takes up more that XX% of a recording in initial scoring, change the WAKE/REM parameters and run again?

What do you guys think?

**Comment by dlevenstein** [comment]
SSM wasn't really designed to be used with recordings without any sleep, which is why this is happening. the algorithm is expecting some amount of time with low EMG (sleep).  but I think it's an easy implementation.  I don't think rescoring is necessary, I can take a look at this at some point using one of your sleepless recordings. in the meantime, it should be easy to use TheStateEditor to just lower the REM/WAKE threshold in the EMG to 0, yes?

**Comment by DavidTingley** [comment]
:1 thanks @dlevenstein, tweaking the threshold (hotkey 'A') works

**Comment by dlevenstein** [comment]
good!  though why you would want to ever work with a recording without any sleep is beyond me ;)

**Comment by brendonw1** [comment]
Does this also solve your problem in the case of no cortex recordings?

**Comment by dlevenstein** [comment]
Didn't you have an alternative SWweights for HPC only recordings Brendon?

**Comment by brendonw1** [comment]
Exactly... well you can at least try... things like notch filters etc.
That's why I was asking David if his scoring was good or not

**Comment by brendonw1** [comment]
Maybe if the regions in the metadata are only hpc or exclude certain things
or whatever one can code it to use a different default frequency band
profile?

**Comment by DavidTingley** [comment]
Changing the EMG threshold fixes this.  In the long run we'll want this logic built in (i.e. recordings should never have >50% REM state) but for now manual adjustment of the threshold is good enough

**Comment by brendonw1** [comment]
OK, what about the suggestion I made of adjusting the criteria used
depending on anatomy?  Is that of interest?
In buzcode I actually already made soemthing called SWweightsHPC.mat... you
can call that as your NREM-determing vector by specifying it in a
name-value pair under the name "SWWeightsName".

SleepScoreMaster('SWWeightsName','SWweightsHPC')

It basically has a notch at Theta

Wanna try that?

**Comment by DavidTingley** [comment]
I'll give it a shot today, how is it different from the 'notchtheta' input argument?

**Comment by brendonw1** [comment]
I think it's the same actually.  Now that I think about it they may be
redundant... they might have been two efforts at the same thing with things
like "notchTheta" being the later version in and effort to be modular and
more function-based rather than overly-specific and combinatorial.

Or maybe I left both of them so people could make custom weights and save
them?
