### ISSUE TITLE
Save multiple wavespec files

### ISSUE THREAD

**Issue by brendonw1** [buzsakilab/buzcode#214]
Need a way to save multiple wavespec files... ie for different channels.  Or to append data from a newly analyzed channel into an old file.  

How should we do this?

Multiple files with different names depending on the lfp channel ie:
.wavespec.channel74.lfp.mat

?

**Comment by AntonioFR8** [comment]
If we are calculating wavelets for the whole recording is probably better to save ch by ch since they are going to be pretty large. The complementary possibility is to save wavelets for many chans only for a fragment of time, then we can save in the same mat. But this later case I think is not the most typical unless you are doing event triggered wavelets, and for that we may have a separate function

**Comment by dlevenstein** [comment]
I'd say add an input option 'saveName' or something, where you can put in an arbitrary name for your saved .lfp.mat file

i.e. 'saveName','WaveChann1' would produce a file baseName.WaveChann1.lfp.mat

**Comment by brendonw1** [comment]
This sounds good.  Unintrusive but gets the job done.  I can make that change when I next use it.

**Comment by brendonw1** [comment]
See pull request #229 to name output files

**Comment by brendonw1** [comment]
I think we've taken care of this with my last commit... unless you want more/different functionality
